# Generated by Django 3.2.19 on 2023-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField()),
                ('total_serials', models.IntegerField()),
                ('products_created', models.IntegerField()),
                ('serials_created', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyCSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(max_length=500)),
                ('state', models.CharField(default=None, max_length=250)),
                ('locality', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=500)),
                ('org_unit', models.CharField(max_length=500)),
                ('common_name', models.CharField(max_length=500)),
                ('duree', models.BigIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('timestamp_epoch_time_start', models.DateTimeField(null=True)),
                ('timestamp_epoch_time_end', models.DateTimeField(null=True)),
            ],
        ),
    ]
