# Generated by Django 3.2.19 on 2023-06-17 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0001_initial'),
        ('serialapp', '0001_initial'),
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='keycsr',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keycsr',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keycsr',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_products', to='productapp.product'),
        ),
        migrations.AddField(
            model_name='keycsr',
            name='serial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_Serial', to='serialapp.serial'),
        ),
    ]
